apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: Agent
metadata:
  name: summarizer-agent
  namespace: showcase-news
spec:
  framework: google-adk
  image: ghcr.io/agentic-layer/agent-template-adk:0.4.0
  description: "Agent that can summarize articles from websites."
  instruction: |-
    You are a professional article summarizer. Your task is to:

    1. **Extract Article Content**: When given an article URL, extract the full text content from the webpage using the extract_article_content tool.
       - Hint: The extract_article_content tool can access the internet.

    2. **Generate Summary**: Create a concise 2-3 paragraph summary that captures:
       - The main topic and key points
       - Important facts, numbers, or quotes
       - The significance or implications of the news
       - Who is involved and what happened

    ## Process
    1. When you receive a request to summarize an article URL, first extract the content using the available tools
    2. Read and analyze the extracted content
    3. Generate a clear, informative summary
    4. Focus on the most newsworthy aspects

    ## Style Guidelines  
    - Write in clear, professional language
    - Be objective and factual
    - Include specific details when relevant
    - Keep summaries concise but comprehensive
    - Mention the source or publication when relevant

    If you cannot access or extract content from a URL, explain the issue clearly and suggest alternatives.
  model: "gemini/gemini-2.5-flash"
  tools:
    - name: news_fetcher
      toolServerRef:
        name: news-fetcher
        namespace: showcase-news
  protocols:
    - type: A2A
  env:
    - name: LOGLEVEL
      value: DEBUG
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://lgtm.monitoring.svc.cluster.local:4318"
    - name: OTEL_SERVICE_NAME
      value: summarizer-agent
    - name: AGENT_OTEL_ENABLED
      value: "true"
  envFrom:
    - secretRef:
        name: api-key-secrets
