apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080
              name: http
          env:
            # Point to the Agent Gateway in showcase-news namespace
            - name: OPENAI_API_BASE_URL
              value: "http://agent-gateway.showcase-news.svc.cluster.local:8080/v1"
            # No API key needed when using Agent Gateway
            - name: OPENAI_API_KEY
              value: "not-needed"
            # Disable authentication for workshop - allows immediate access without login
            - name: WEBUI_AUTH
              value: "False"
            - name: ENABLE_VERSION_UPDATE_CHECK
              value: "False"
          volumeMounts:
            - name: data
              mountPath: /app/backend/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: openwebui
spec:
  selector:
    app: open-webui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
